name: E2E tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'

      - name: Create .env file
        run: |
          echo "SERVER_PORT=8084" > ./2FA/.env
          echo "SENDER_EMAIL_ADDRESS=${{ secrets.SENDER_EMAIL_ADDRESS }}" >> ./2FA/.env
          echo "SENDER_EMAIL_PASSWORD=${{ secrets.SENDER_EMAIL_PASSWORD }}" >> ./2FA/.env
          echo "SMTP_SERVER=${{ secrets.SMTP_SERVER }}" >> ./2FA/.env
          echo "RECIPIENT_EMAIL_ADDRESS=${{ secrets.RECIPIENT_EMAIL_ADDRESS }}" >> ./2FA/.env
          echo "TEST=false" >> ./2FA/.env

      - name: Run tests
        run: cd ./2FA && make run-tests
